# Generated by Django 3.1.2 on 2020-10-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('mensaje', models.TextField(max_length=2000)),
                ('correo', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('apep', models.CharField(max_length=20)),
                ('apem', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=9)),
                ('edad', models.IntegerField(max_length=9)),
                ('cantP', models.IntegerField(max_length=3)),
                ('telef', models.IntegerField(max_length=9)),
                ('destinos', models.CharField(blank=True, choices=[('NA', 'Selecciona un destino'), ('HAWAI', 'Hawai'), ('PARIS', 'Paris'), ('MOSCY', 'Moscu'), ('TOKIO', 'Tokio'), ('SHANGAI', 'Shangai'), ('BERLIN', 'Berlin'), ('DUBAI', 'Dubai')], default='NA', help_text='Destinos', max_length=21)),
            ],
        ),
    ]
